#!/usr/bin/env python3
"""Derive the disaster scene from the Gazebo world, into a committed module.

The scene existed in three places that had to agree and didn't: the world file
(29 damaged structures), `SwarmGymEnv._DISASTER_STRUCTURES` (17 of them, by
hand), and the coverage grid bounds in two YAML configs. The gym's list was
missing the reactor, both water towers, all three radio towers, five collapsed
industrial buildings and a police station — so the importance map, and
therefore the reward, was built from a reactor-free subset of the disaster.

Hand-copying 29 coordinates is how that happened, so this generates them.
Run it when the world changes:

    python3 scripts/generate_disaster_scene.py

and commit the result. `test_disaster_scene.py` re-derives the scene and fails
if the committed module has drifted from the world, so a world edit without a
regenerate is caught in CI rather than in a coverage figure months later.
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys
import xml.etree.ElementTree as ET
from typing import Dict, List, Tuple

REPO = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_WORLD = 'earthquake_city'
DEFAULT_OUTPUT = (REPO / 'src/aura_strategic_rl/aura_strategic_rl'
                  / 'disaster_scene.py')

#: Models that are scenery or infrastructure rather than damaged structures
#: needing coverage. Kept explicit: silently dropping things by heuristic is
#: how a list ends up wrong.
NOT_STRUCTURES = frozenset({
    'ground_plane', 'sun', 'simple_baylands', 'asphalt_plane',
    'launch_pad', 'h_marker', 'ambulance', 'bus',
})

#: Radius over which a structure raises coverage importance (3x in the gym
#: env). Also the margin the coverage grid takes around the scene: a responder
#: within this distance of a structure is inside the area that matters.
IMPORTANCE_RADIUS_M = 50.0

#: Coverage grid cell size. Grid bounds are snapped to this.
GRID_RESOLUTION_M = 10.0


def world_path(world: str) -> pathlib.Path:
    return REPO / 'worlds' / f'{world}.world'


def parse_structures(path: pathlib.Path) -> List[Tuple[str, float, float]]:
    """Damaged structures and their ENU x, y, from a Gazebo world.

    Only direct children of <world> are read. A world also carries a <state>
    block that repeats every model with its runtime pose, and `simple_baylands`
    nests its own models — both would double-count under a flat search.
    """
    root = ET.parse(path).getroot()
    world = root.find('world')
    if world is None:
        raise ValueError(f'{path} has no <world> element')

    found: Dict[str, Tuple[float, float]] = {}
    for model in world.findall('model'):
        name = model.get('name')
        if not name or name in NOT_STRUCTURES:
            continue
        pose = model.find('pose')
        if pose is None or not pose.text:
            continue
        parts = pose.text.split()
        if len(parts) < 2:
            continue
        if name in found:
            raise ValueError(f'{path}: duplicate model name {name!r}')
        # Round to millimetres: the rendered module prints 3 decimals, and a
        # generated file has to be exactly what re-parsing produces or the
        # staleness check can never pass.
        found[name] = (round(float(parts[0]), 3), round(float(parts[1]), 3))

    return [(name, xy[0], xy[1]) for name, xy in sorted(found.items())]


def bbox(structures) -> Tuple[float, float, float, float]:
    xs = [x for _, x, _ in structures]
    ys = [y for _, _, y in structures]
    return (min(xs), min(ys), max(xs), max(ys))


def grid_bounds(structures, margin=IMPORTANCE_RADIUS_M,
                snap=GRID_RESOLUTION_M) -> Tuple[float, float, float, float]:
    """Coverage grid: the scene's bounding box plus `margin`, snapped to cells.

    Fitted to the scene rather than squared off around a centre. The coverage
    percentage is a fraction of grid cells, so empty area straight up dilutes
    it — a square grid here would be 40% ground with nothing on it.
    """
    x_min, y_min, x_max, y_max = bbox(structures)
    return (math.floor((x_min - margin) / snap) * snap,
            math.floor((y_min - margin) / snap) * snap,
            math.ceil((x_max + margin) / snap) * snap,
            math.ceil((y_max + margin) / snap) * snap)


def render(world: str, structures) -> str:
    x_min, y_min, x_max, y_max = bbox(structures)
    gx_min, gy_min, gx_max, gy_max = grid_bounds(structures)

    lines = [
        '"""The disaster scene, derived from the Gazebo world.',
        '',
        'GENERATED by scripts/generate_disaster_scene.py — do not edit by hand.',
        f'Source: worlds/{world}.world',
        '',
        'Regenerate after changing the world, and commit the result.',
        'test_disaster_scene.py re-derives this and fails if the two disagree.',
        '"""',
        '',
        'from typing import List, Tuple',
        '',
        f'WORLD = {world!r}',
        f'SOURCE = {f"worlds/{world}.world"!r}',
        '',
        '#: Radius over which a structure raises coverage importance, and the',
        '#: margin GRID_BOUNDS takes around the scene.',
        f'IMPORTANCE_RADIUS_M = {IMPORTANCE_RADIUS_M!r}',
        '',
        f'GRID_RESOLUTION_M = {GRID_RESOLUTION_M!r}',
        '',
        f'#: Damaged structures needing coverage: {len(structures)} of them,',
        '#: as (name, x, y) in ENU metres.',
        'STRUCTURES: List[Tuple[str, float, float]] = [',
    ]
    width = max(len(name) for name, _, _ in structures) + 2
    for name, x, y in structures:
        lines.append(f'    ({name!r:<{width}}, {x:9.3f}, {y:9.3f}),')
    lines += [
        ']',
        '',
        '#: Tight bounding box of the structures: (x_min, y_min, x_max, y_max).',
        f'BBOX = ({x_min!r}, {y_min!r}, {x_max!r}, {y_max!r})',
        '',
        '#: Coverage grid bounds: BBOX plus IMPORTANCE_RADIUS_M, snapped to',
        f'#: GRID_RESOLUTION_M. {int((gx_max - gx_min) / GRID_RESOLUTION_M)}'
        f' x {int((gy_max - gy_min) / GRID_RESOLUTION_M)} cells.',
        f'GRID_BOUNDS = ({gx_min!r}, {gy_min!r}, {gx_max!r}, {gy_max!r})',
        '',
        '',
        'def structure_xy() -> List[Tuple[float, float]]:',
        '    """Just the coordinates, for importance-map construction."""',
        '    return [(x, y) for _, x, y in STRUCTURES]',
        '',
    ]
    return '\n'.join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--world', default=DEFAULT_WORLD,
                    help=f'world name under worlds/ (default: {DEFAULT_WORLD})')
    ap.add_argument('--output', type=pathlib.Path, default=DEFAULT_OUTPUT)
    ap.add_argument('--check', action='store_true',
                    help='exit non-zero if the output is stale, writing nothing')
    args = ap.parse_args(argv)

    path = world_path(args.world)
    if not path.exists():
        print(f'no such world: {path}', file=sys.stderr)
        return 2

    structures = parse_structures(path)
    if not structures:
        print(f'{path}: no structures found', file=sys.stderr)
        return 2
    rendered = render(args.world, structures)

    if args.check:
        current = args.output.read_text() if args.output.exists() else ''
        if current != rendered:
            print(f'{args.output} is stale — run '
                  f'scripts/generate_disaster_scene.py', file=sys.stderr)
            return 1
        print(f'{args.output} is up to date ({len(structures)} structures)')
        return 0

    args.output.write_text(rendered)
    x_min, y_min, x_max, y_max = bbox(structures)
    gx_min, gy_min, gx_max, gy_max = grid_bounds(structures)
    print(f'wrote {args.output}')
    print(f'  world      : {args.world}')
    print(f'  structures : {len(structures)}')
    print(f'  bbox       : x[{x_min:.1f}, {x_max:.1f}] '
          f'y[{y_min:.1f}, {y_max:.1f}]  '
          f'({x_max - x_min:.0f} x {y_max - y_min:.0f} m)')
    print(f'  grid       : x[{gx_min:.0f}, {gx_max:.0f}] '
          f'y[{gy_min:.0f}, {gy_max:.0f}]  '
          f'({int((gx_max - gx_min) / GRID_RESOLUTION_M)} x '
          f'{int((gy_max - gy_min) / GRID_RESOLUTION_M)} cells '
          f'at {GRID_RESOLUTION_M:.0f} m)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
