"""The disaster scene, derived from the Gazebo world.

GENERATED by scripts/generate_disaster_scene.py — do not edit by hand.
Source: worlds/earthquake_city.world

Regenerate after changing the world, and commit the result.
test_disaster_scene.py re-derives this and fails if the two disagree.
"""

from typing import List, Tuple

WORLD = 'earthquake_city'
SOURCE = 'worlds/earthquake_city.world'

#: Radius over which a structure raises coverage importance, and the
#: margin GRID_BOUNDS takes around the scene.
IMPORTANCE_RADIUS_M = 50.0

GRID_RESOLUTION_M = 10.0

#: Damaged structures needing coverage: 29 of them,
#: as (name, x, y) in ENU metres.
STRUCTURES: List[Tuple[str, float, float]] = [
    ('collapsed_house'           ,   290.643,  -242.997),
    ('collapsed_house_0'         ,   289.857,  -219.095),
    ('collapsed_house_1'         ,   289.526,  -193.189),
    ('collapsed_house_10'        ,   154.904,  -194.142),
    ('collapsed_house_2'         ,   314.622,  -243.343),
    ('collapsed_house_3'         ,   312.796,  -217.632),
    ('collapsed_house_4'         ,   262.917,  -237.019),
    ('collapsed_house_5'         ,   121.275,  -106.388),
    ('collapsed_house_6'         ,    67.802,   -87.956),
    ('collapsed_house_7'         ,    45.361,  -117.764),
    ('collapsed_house_8'         ,    87.274,  -142.339),
    ('collapsed_house_9'         ,   155.300,  -227.557),
    ('collapsed_industrial'      ,    58.270,  -256.028),
    ('collapsed_industrial_0'    ,    57.250,  -191.370),
    ('collapsed_industrial_1'    ,   -36.552,  -218.114),
    ('collapsed_industrial_2'    ,    13.614,  -234.810),
    ('collapsed_industrial_3'    ,    12.157,  -197.870),
    ('collapsed_industrial_4'    ,    77.941,  -216.127),
    ('collapsed_industrial_5'    ,   114.582,  -236.776),
    ('collapsed_police_station'  ,   194.999,  -239.791),
    ('collapsed_police_station_0',   201.865,  -115.071),
    ('playground'                ,   178.738,  -287.445),
    ('radio_tower'               ,   338.205,  -294.738),
    ('radio_tower_0'             ,   -87.957,  -189.362),
    ('radio_tower_1'             ,   185.245,   -33.181),
    ('reactor'                   ,  -112.436,   -77.753),
    ('school'                    ,   195.846,  -150.083),
    ('water_tower'               ,   244.874,  -239.288),
    ('water_tower_0'             ,    -2.428,  -115.991),
]

#: Tight bounding box of the structures: (x_min, y_min, x_max, y_max).
BBOX = (-112.436, -294.738, 338.205, -33.181)

#: Coverage grid bounds: BBOX plus IMPORTANCE_RADIUS_M, snapped to
#: GRID_RESOLUTION_M. 56 x 37 cells.
GRID_BOUNDS = (-170.0, -350.0, 390.0, 20.0)


def structure_xy() -> List[Tuple[float, float]]:
    """Just the coordinates, for importance-map construction."""
    return [(x, y) for _, x, y in STRUCTURES]
